### ISSUE TITLE
Síntesis Webinar Gestión de Proyectos de Software

### ISSUE THREAD

**Issue by dulce-blm** [SistemasTecTlaxiaco/sintesis-dulce-blm#2]
[Sintesis.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-dulce-blm/files/7118848/Sintesis.pdf)

**Comment by Graciela2000** [comment]
Calificación: 20%
Calificó: Graciela Hernández Santiago

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado...
